<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:discourse="http://www.discourse.org/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Installation - PySpice</title>
    <link>https://pyspice.discourse.group/c/installation/10</link>
    <description>Topics in the &#39;Installation&#39; category </description>
    
      <lastBuildDate>Thu, 11 Nov 2021 13:45:39 +0000</lastBuildDate>
      <atom:link href="https://pyspice.discourse.group/c/installation/10.rss" rel="self" type="application/rss+xml" />
        <item>
          <title>Problems with running simulator</title>
          <dc:creator><![CDATA[AMK]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>Hi every one!<br>
I am new to PySpice. I was running 1.4.3 ver with ngspice 3.2 and everything was working well.<br>
My computer did a usual clean up and update.</p>
<p>Now the netlist part works fine. But when I call the simulator I get a long error message (I will paste below). I was doing good progress and I am glad to share a 3 phase diode rectifier model which was working well. Until this problem arose. When I did an update I see that the cur ver is 1.5 and installs ngspice 3.4</p>
<p>Any help is appreciated. Else will have to go back to LTspice</p>
<p>Error msg attached below</p>
<hr>
<p>TypeError                                 Traceback (most recent call last)<br>
 in <br>
----&gt; 1 simulator = circuit3.simulator(temperature=25, nominal_temperature=25)<br>
2 simulator.initial_condition(out = 90@u_V)<br>
3 analysis = simulator.transient(step_time=Vac.period/1000, end_time=Vac.period*6)<br>
4<br>
5 res = format_output(analysis)</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\Netlist.py in simulator(self, *args, **kwargs)</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\Simulation.py in factory(cls, circuit, *args, **kwargs)<br>
1117     “”" This class implements a circuit simulator. Each analysis mode is performed by a method that<br>
1118     return the measured probes.<br>
 → 1119<br>
1120     For <em>ac</em> and <em>transient</em> analyses, the user must specify a list of nodes using the <em>probes</em> key<br>
1121     argument.</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Simulation.py in <strong>init</strong>(self, circuit, **kwargs)<br>
97         ngspice_shared = kwargs.get(‘ngspice_shared’, None)<br>
98         if ngspice_shared is None:<br>
—&gt; 99             self._ngspice_shared = NgSpiceShared.new_instance()<br>
100         else:<br>
101             self._ngspice_shared = ngspice_shared</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Shared.py in new_instance(cls, ngspice_id, send_data, verbose)<br>
450             cls._instances[ngspice_id] = instance<br>
451             return instance<br>
 → 452<br>
453     ##############################################<br>
454</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Shared.py in <strong>init</strong>(self, ngspice_id, send_data, verbose)<br>
478         self._library_path = None<br>
479         self._load_library(verbose)<br>
 → 480         self._init_ngspice(send_data)<br>
481<br>
482         self._is_running = False</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Shared.py in _load_library(self, verbose)<br>
511             if ‘SPICE_LIB_DIR’ not in os.environ:<br>
512                 _ = str(Path(self.NGSPICE_PATH).joinpath(‘share’, ‘ngspice’))<br>
 → 513                 os.environ[‘SPICE_LIB_DIR’] = _<br>
514                 # self._logger.warning(‘Set SPICE_LIB_DIR = %s’, _)<br>
515</p>
<p>~\Anaconda3\lib\pathlib.py in <strong>new</strong>(cls, *args, **kwargs)<br>
1036         if cls is Path:<br>
1037             cls = WindowsPath if os.name == ‘nt’ else PosixPath<br>
 → 1038         self = cls._from_parts(args, init=False)<br>
1039         if not self._flavour.is_supported:<br>
1040             raise NotImplementedError(“cannot instantiate %r on your system”</p>
<p>~\Anaconda3\lib\pathlib.py in _from_parts(cls, args, init)<br>
677         # right flavour.<br>
678         self = object.<strong>new</strong>(cls)<br>
 → 679         drv, root, parts = self._parse_args(args)<br>
680         self._drv = drv<br>
681         self._root = root</p>
<p>~\Anaconda3\lib\pathlib.py in _parse_args(cls, args)<br>
661                 parts += a._parts<br>
662             else:<br>
 → 663                 a = os.fspath(a)<br>
664                 if isinstance(a, str):<br>
665                     # Force-cast str subclasses to str (issue <span class="hashtag">#21127</span>)</p>
<p>TypeError: expected str, bytes or os.PathLike object, not NoneType</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/problems-with-running-simulator/153">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/problems-with-running-simulator/153</link>
          <pubDate>Thu, 11 Nov 2021 13:45:39 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-153</guid>
          <source url="https://pyspice.discourse.group/t/problems-with-running-simulator/153.rss">Problems with running simulator</source>
        </item>
        <item>
          <title>Getting keyerror while running example</title>
          <dc:creator><![CDATA[Sky77]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>As i’m new to pyspice when i am running this example<br>
<a href="https://pyspice.fabrice-salvaire.fr/releases/v1.3/examples/diode/diode-characteristic-curve.html" rel="noopener nofollow ugc">https://pyspice.fabrice-salvaire.fr/releases/v1.3/examples/diode/diode-characteristic-curve.html</a></p>
<p>I am getting this keyerror </p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/free1/uploads/pyspice/original/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372.jpeg" data-download-href="/uploads/short-url/wEDXbmSH7xJG7wRDx5Jm9EdbCWm.jpeg?dl=1" title="IMG_20210130_184031" rel="noopener nofollow ugc"><img src="https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_477x500.jpeg" alt="IMG_20210130_184031" data-base62-sha1="wEDXbmSH7xJG7wRDx5Jm9EdbCWm" width="477" height="500" srcset="https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_477x500.jpeg, https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_715x750.jpeg 1.5x, https://aws1.discourse-cdn.com/free1/uploads/pyspice/original/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372.jpeg 2x" data-small-upload="https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_10x10.png"></a></div><p></p>
<p>I m using windows 10 64 bit<br>
Ide : Anaconda python<br>
Pyspice 1.4.3<br>
Ngspice 32</p>
<p>If any gentlemen has idea how to fix this it ll help me a lot <img src="https://emoji.discourse-cdn.com/twitter/smiley.png?v=9" title=":smiley:" class="emoji" alt=":smiley:"></p>
            <p><small>4 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/getting-keyerror-while-running-example/119">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/getting-keyerror-while-running-example/119</link>
          <pubDate>Sat, 30 Jan 2021 13:14:32 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-119</guid>
          <source url="https://pyspice.discourse.group/t/getting-keyerror-while-running-example/119.rss">Getting keyerror while running example</source>
        </item>
        <item>
          <title>Installation example scripts</title>
          <dc:creator><![CDATA[cyber-g]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>Dear PySpice community, I would like to share some installation example files to illustrate the installation procedure of PySpice on Linux by using <code>apt</code> and <code>pip</code> only.</p>
<p>Those files are published as Dockerfile scripts since they allow full automatic machine instantiation with <code>docker</code>.<br>
They cover both Ubuntu and Debian, using a standard approach using only <code>apt</code> :</p>
<ul>
<li><a href="https://github.com/cyber-g/debian-pyspice-std" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/debian-pyspice-std: A Dockerfile to demonstrate the installation of PySpice on Debian</a></li>
<li><a href="https://github.com/cyber-g/ubuntu-pyspice-std" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/ubuntu-pyspice-std: A Dockerfile to demonstrate the installation of PySpice on Ubuntu</a></li>
</ul>
<p>One can also find a more “manual” approach to demonstrate how to properly set the <code>PYTHONPATH</code> and <code>LD_LIBRARY_PATH</code> environment variables :</p>
<ul>
<li><a href="https://github.com/cyber-g/debian-pyspice-semi-custom" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/debian-pyspice-semi-custom: A Dockerfile to demonstrate the installation of PySpice on Debian using a "manual" installation of libngspice</a></li>
<li><a href="https://github.com/cyber-g/ubuntu-pyspice-semi-custom" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/ubuntu-pyspice-semi-custom: A Dockerfile to demonstrate the installation of PySpice on Ubuntu using a "manual" installation of libngspice</a></li>
</ul>
<p>The two latter should be useful for those who want to install PySpice on Google Collab.</p>
<p>If you have docker on your computer, you can also pull directly the images from Docker Hub :</p>
<ul>
<li><a href="https://hub.docker.com/repository/docker/drdpham/pyspice-debian" rel="noopener nofollow ugc">Docker Hub PySpice Debian</a></li>
<li><a href="https://hub.docker.com/repository/docker/drdpham/pyspice-ubuntu" rel="noopener nofollow ugc">Docker Hub PySpice Ubuntu</a></li>
</ul>
<p>Enjoy !</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/installation-example-scripts/117">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/installation-example-scripts/117</link>
          <pubDate>Mon, 25 Jan 2021 22:35:44 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-117</guid>
          <source url="https://pyspice.discourse.group/t/installation-example-scripts/117.rss">Installation example scripts</source>
        </item>
        <item>
          <title>Two installation experiences on Windows</title>
          <dc:creator><![CDATA[endolith]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <h2>Windows 10</h2>
<p>First I tried to install in my base conda environment on Windows 10 64-bit.  It could not be installed due to package conflicts and it tried many different things to resolve the conflicts, grinding away at the CPU for two hours, and eventually I killed it.</p>
<p>Then I created a new environment specifically for PySpice and installed it:</p>
<pre><code class="lang-auto">conda create --name pyspice
conda activate pyspice
conda install -c conda-forge pyspice
pyspice-post-installation --install-ngspice-dll
</code></pre>
<p>This last step did not work, however, because it required the<br>
<code>requests</code> library:</p>
<pre><code class="lang-auto">ModuleNotFoundError: No module named 'requests'
</code></pre>
<p>So I then did</p>
<pre><code class="lang-auto">conda install requests
pyspice-post-installation --install-ngspice-dll
pyspice-post-installation --check-install
</code></pre>
<p>And it worked.  I reported the dependency problem here: <a href="https://github.com/FabriceSalvaire/PySpice/issues/266" rel="noopener nofollow ugc">https://github.com/FabriceSalvaire/PySpice/issues/266</a></p>
<h2>Windows 7</h2>
<p>Now I’m doing the same procedure on a Windows 7 machine (I know, I know, it’s obsolete).  The install command showed no errors on the command line, but I did get a pop up error:</p>
<blockquote>
<p>python.exe - System Error</p>
<p>The program can’t start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.</p>
<p>OK</p>
</blockquote>
<p>I haven’t seen this error before, but the install command worked so I’m ignoring it.</p>
<p>Then I try</p>
<pre><code class="lang-auto">pyspice-post-installation --install-ngspice-dll
</code></pre>
<p>Ah, now I’m getting the same error:</p>
<blockquote>
<p>python.exe - System Error</p>
<p>The program can’t start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.</p>
<p>OK</p>
</blockquote>
<p>and if I run the check:</p>
<pre><code class="lang-auto">pyspice-post-installation --check-install
</code></pre>
<p>I get the same error dialog:</p>
<blockquote>
<p>python.exe - System Error</p>
<p>The program can’t start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.</p>
<p>OK</p>
</blockquote>
<p>Tried System File Checker:</p>
<pre><code class="lang-auto">λ sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection did not find any integrity violations.
</code></pre>
<p>Searching my machine, it does not have <code>api-ms-win-core-path-l1-1-0.dll</code> anywhere.  Maybe this is a Windows 10 file only.  (Nope, not present on Windows 10 machine, either.)</p>
<p>Trying to install jupyterlab also doesn’t work well.  Does PySpice have some weird requirements/dependencies that prevent conda from installing it alongside other things?</p>
<pre><code class="lang-auto">Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
</code></pre>
<p>Oh if I do it as <code>conda install jupyterlab voila</code> instead of using conda-forge, it works fine</p>
            <p><small>2 posts - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/two-installation-experiences-on-windows/107">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/two-installation-experiences-on-windows/107</link>
          <pubDate>Wed, 16 Dec 2020 15:28:34 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-107</guid>
          <source url="https://pyspice.discourse.group/t/two-installation-experiences-on-windows/107.rss">Two installation experiences on Windows</source>
        </item>
        <item>
          <title>Load_circuit failing for some reasons</title>
          <dc:creator><![CDATA[asav86]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <hr>
<ul>
<li>OS: MacOS Catilina (version 10.15.7)</li>
<li>Python framework with PyCharm + Conda environment</li>
<li>PySpice installed with Conda (version 1.4.3)</li>
<li>libngspice installed with Conda</li>
<li>NGSPICE installed with homebrew (version 33)
<ul>
<li>location: /usr/local/bin/ngspice</li>
<li>functionality check: NGSPICE works from terminal and does simulate a circuit</li>
</ul>
</li>
</ul>
<hr>
<p>Hi,</p>
<p>this is my first test with the “PySpice” flow. I went through the explained installation steps:</p>
<aside class="onebox allowlistedgeneric">
  <header class="source">
      <a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/installation.html" target="_blank" rel="noopener nofollow ugc">pyspice.fabrice-salvaire.fr</a>
  </header>
  <article class="onebox-body">
    <img src="" class="thumbnail" width="" height="">

<h3><a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/installation.html" target="_blank" rel="noopener nofollow ugc">4. Installation — PySpice 1.4.2 documentation</a></h3>



  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

<p>By running the “resistor-bridge.py” example:</p>
<aside class="onebox allowlistedgeneric">
  <header class="source">
      <a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/examples/resistor/resistor-bridge.html" target="_blank" rel="noopener nofollow ugc">pyspice.fabrice-salvaire.fr</a>
  </header>
  <article class="onebox-body">
    <img src="" class="thumbnail" width="" height="">

<h3><a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/examples/resistor/resistor-bridge.html" target="_blank" rel="noopener nofollow ugc">8.15.1. Resistor Bridge — PySpice 1.4.2 documentation</a></h3>



  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

<p>I get the following error:</p>
<p>…<br>
PySpice.Spice.NgSpice.Shared.NgSpiceCommandError: Command ‘run’ failed<br>
…</p>
<p>By placing a breakpoint and debugging the code I see that the failing point is at (every line nested hierarchically):</p>
<p>analysis = simulator.operating_point()<br>
return self._run(‘operating_point’, *args, **kwargs)<br>
self._ngspice_shared.run()<br>
self.exec_command(command)<br>
raise NgSpiceCommandError(“Command ‘{}’ failed”.format(command))</p>
<p>And is due to stderr = ‘Error: there aren’t any circuits loaded.’</p>
<p>By debugging further I could nail down that the def run() method of the Simulation class fails because the run command after the load_circuit command complains that the circuit wasn’t loaded.</p>
<pre><code>def _run(self, analysis_method, *args, **kwargs):

    super()._run(analysis_method, *args, **kwargs)

    self._ngspice_shared.destroy()
    # Fixme: Error: circuit not parsed.
    self._ngspice_shared.load_circuit(str(self))
    self._ngspice_shared.run()
    self._logger.debug(str(self._ngspice_shared.plot_names))
    self.reset_analysis()

    plot_name = self._ngspice_shared.last_plot
    if plot_name == 'const':
        raise NameError('Simulation failed')

    return self._ngspice_shared.plot(self, plot_name).to_analysis()
</code></pre>
<p>So the load_circuit method seems to not load the circuit properly in the sim, any idea why? (although it does execute it and no error is raised within that method).</p>
<p>I tried also the listing() method to query the circuit description back and also doesn’t seem to provide anything back.</p>
<p>Actually the only communication with the simulator seems to be successful is the “version -f” command which returns the valuable infos from it.</p>
<p>Thanks,<br>
Andrea</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/load-circuit-failing-for-some-reasons/96">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/load-circuit-failing-for-some-reasons/96</link>
          <pubDate>Mon, 02 Nov 2020 20:14:10 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-96</guid>
          <source url="https://pyspice.discourse.group/t/load-circuit-failing-for-some-reasons/96.rss">Load_circuit failing for some reasons</source>
        </item>
        <item>
          <title>Install Pyspice on Raspberry Pi 4 ERROR</title>
          <dc:creator><![CDATA[LencsesDaniel]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>Hello Everyone!<br>
I’m running into a problem, i want to install PySpice on Raspberry Pi 4 which runs Raspbian OS. I have read the doumentation that wrote, it is supported on Linux, Windos 64 and MAC.<br>
I have followed the install instructions after i typed : pip3 install PySpice the following error message i got:</p>
<p>Defaulting to user installation because normal site-packages is not writeable<br>
Looking in indexes: <a href="https://pypi.org/simple" rel="noopener nofollow ugc">https://pypi.org/simple</a>, <a href="https://www.piwheels.org/simple" rel="noopener nofollow ugc">https://www.piwheels.org/simple</a><br>
Collecting PySpice<br>
Using cached PySpice-1.4.3-py2.py3-none-any.whl (144 kB)<br>
Collecting scipy&gt;=1.4<br>
Downloading scipy-1.5.3.tar.gz (25.2 MB)<br>
|################################| 25.2 MB 28 kB/s<br>
Installing build dependencies … \Ledone<br>
Getting requirements to build wheel … done<br>
Preparing wheel metadata … error<br>
ERROR: Command errored out with exit status 1:<br>
command: /usr/bin/python /home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpv39ep59r<br>
cwd: /tmp/pip-install-_1dtpvzc/scipy<br>
Complete output (139 lines):<br>
lapack_opt_info:<br>
lapack_mkl_info:<br>
customize UnixCCompiler<br>
libraries mkl_rt not found in [’/usr/local/lib’, ‘/usr/lib’, ‘/usr/lib/arm-linux-gnueabihf’]<br>
NOT AVAILABLE</p>
<pre><code>openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

openblas_clapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

flame_info:
customize UnixCCompiler
  libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_3_10_threads_info'&gt;
  NOT AVAILABLE

atlas_3_10_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_3_10_info'&gt;
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_threads_info'&gt;
  NOT AVAILABLE

atlas_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_info'&gt;
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

lapack_info:
customize UnixCCompiler
  libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

lapack_src_info:
  NOT AVAILABLE

  NOT AVAILABLE

setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-yx7fyy34'), proceeding with generating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
Running from SciPy source directory.
/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  if getattr(self, '_calc_info_{}'.format(lapack))():
/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  if getattr(self, '_calc_info_{}'.format(lapack))():
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in &lt;module&gt;
    main()
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
    return hook(metadata_directory, config_settings)
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
    self.run_setup()
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 583, in &lt;module&gt;
    setup_package()
  File "setup.py", line 579, in setup_package
    setup(**metadata)
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 477, in configuration
    raise NotFoundError(msg)
numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
----------------------------------------
</code></pre>
<p>ERROR: Command errored out with exit status 1: /usr/bin/python /home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpv39ep59r Check the logs for full command output.</p>
<p>Is it because i have <a href="https://en.wikipedia.org/wiki/ARM_Cortex-A72" rel="noopener nofollow ugc">ARM Cortex-A72</a> architecture and not x64? Or is it because Raspbian and not exactly Linux? But raspbian based on Linux…</p>
<p>Thanks for all answers!<br>
Best regards,<br>
Daniel</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/install-pyspice-on-raspberry-pi-4-error/90">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/install-pyspice-on-raspberry-pi-4-error/90</link>
          <pubDate>Mon, 19 Oct 2020 17:38:42 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-90</guid>
          <source url="https://pyspice.discourse.group/t/install-pyspice-on-raspberry-pi-4-error/90.rss">Install Pyspice on Raspberry Pi 4 ERROR</source>
        </item>
        <item>
          <title>Linux installation of libngspice</title>
          <dc:creator><![CDATA[Damian]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>Hi,</p>
<p>Im having trouble installing libngspice on ubuntu 19.04 with anaconda v4.8.2.<br>
I have ngpsice installed (sudo apt-get install ngspice).<br>
Then I’m following instructions on pyspice <a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/installation.html#installation-page" rel="noopener nofollow ugc">install</a></p>
<p>Im happy to use anaconda so I skipped to section 4.2.2<br>
However the following commands run for many hours without success</p>
<blockquote>
<p>conda install -c conda-forge ngspice-lib # optional<br>
conda install -c conda-forge pyspice</p>
</blockquote>
<p>with messages like:</p>
<blockquote>
<p>Collecting package metadata (current_repodata.json): done<br>
Solving environment: /<br>
The environment is inconsistent, please check the package plan carefully<br>
The following packages are causing the inconsistency:<br>
:::::</p>
</blockquote>
<p>Trying the other command seems to work.</p>
<blockquote>
<p>pip install PySpice</p>
</blockquote>
<p>but this one doesn’t include libngspice.</p>
<p>Going back to step 4.2.1<br>
I downloaded a tar of the libngspice but it’s a tar’d directory not a shared object (.so).<br>
There’s no instructions in that directory on how to compile it… or where I should<br>
place it for pyspice?</p>
<p>I found a similar question on this pyspice <a href="https://pyspice.discourse.group/t/oserror-cannot-load-library-libngspice-so/37/7">forum</a> and I tried</p>
<blockquote>
<p>inv ngspice.install<br>
::::<br>
configure: error: Couldn’t find GNU readline headers.</p>
</blockquote>
<p>I guess I need to do something like</p>
<blockquote>
<p>sudo apt-get install lib64readline</p>
</blockquote>
<p>But I’ve not been able to locate that package so far…<br>
Any ideas? I don’t think I’m going in the right direction?</p>
<p>A+</p>
<p>Damian</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/linux-installation-of-libngspice/84">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/linux-installation-of-libngspice/84</link>
          <pubDate>Fri, 25 Sep 2020 14:59:25 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-84</guid>
          <source url="https://pyspice.discourse.group/t/linux-installation-of-libngspice/84.rss">Linux installation of libngspice</source>
        </item>
        <item>
          <title>About the Installation category</title>
          <dc:creator><![CDATA[fsalvaire]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>(Replace this first paragraph with a brief description of your new category. This guidance will appear in the category selection area, so try to keep it below 200 characters.)</p>
<p>Use the following paragraphs for a longer description, or to establish category guidelines or rules:</p>
<ul>
<li>
<p>Why should people use this category? What is it for?</p>
</li>
<li>
<p>How exactly is this different than the other categories we already have?</p>
</li>
<li>
<p>What should topics in this category generally contain?</p>
</li>
<li>
<p>Do we need this category? Can we merge with another category, or subcategory?</p>
</li>
</ul>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/about-the-installation-category/17">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/about-the-installation-category/17</link>
          <pubDate>Mon, 27 Apr 2020 19:49:08 +0000</pubDate>
          <discourse:topicPinned>Yes</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-17</guid>
          <source url="https://pyspice.discourse.group/t/about-the-installation-category/17.rss">About the Installation category</source>
        </item>
  </channel>
</rss>
